### ISSUE TITLE
See through world

### ISSUE THREAD

**Issue by knightfury3000** [LunaPixelStudios/Fantasy-Realm#10]
### Describe the Bug

For some reason, whenever I joined the world, I could sometimes see through blocks(like an xray modpack, but not every block was see through). It was usually in large chunks, almost as if the block face culling was working improperly. So naturally I turned that off, and turned off the resource packs I myself had personally added to no avail. I created a new world even with my resource packs uninstalled beforehand, nothing seemed to make it work. As of right now, I am reinstalling the modpack to see if that changes anything(I sometimes add other mods I usually want, so I may have added some before I had updated the pack without realizing it). Wish me luck, and I hope the pack works!

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V6

### Optifine

No

### Other Mods

Possibly? Don't know quite yet, hopefully not though

**Comment by knightfury3000** [comment]
It seems the issue persists across instances, will keep looking into this.

**Comment by knightfury3000** [comment]
Unfortunately, uninstalling all resource packs has no effect on the issue(including prepackaged ones), proceeding with investigation.

**Comment by SHXRKIEgg** [comment]
Could oyu provide and image?

**Comment by knightfury3000** [comment]
Right, of course, my apologies

**Comment by knightfury3000** [comment]
![2022-09-05_12 05 39](https://user-images.githubusercontent.com/76122153/188618876-eb3dd8ef-264f-478c-9486-ccfc0da3cd13.png)

**Comment by knightfury3000** [comment]
![2022-09-05_12 05 49](https://user-images.githubusercontent.com/76122153/188618920-13c95fd1-55ec-49f4-bb8f-b5274d8a9563.png)

**Comment by knightfury3000** [comment]
![2022-09-05_12 06 05](https://user-images.githubusercontent.com/76122153/188618954-d31ce6c0-9b96-4043-9856-92f3dc43e8af.png)

**Comment by knightfury3000** [comment]
the GUI seems to be working perfectly fine, as does the textures on mobs and items, it's only the actual terrain that is having an issue

**Comment by chorbintime** [comment]
Have you tried reloading chunks with F3 + A? You could also find common solutions to this problem on Vanilla Minecraft which would likely apply here too.

**Comment by knightfury3000** [comment]
I attempted the f3+A solution, which also seemed ineffective, I will look into other fixes for this issue
