### ISSUE TITLE
Minecraft client crash (FTBchunks problem)

### ISSUE THREAD

**Issue by Annihilluss** [LunaPixelStudios/Fantasy-Realm#11]
### Describe the Bug

Hello i would like to report a bug that me and my friends ran into when joining a bought Fantasy realm server.

When me or my friends want to join the server that we bought the minecraft client crashes with this message: 

Error: java.lang.NullPointerException: Unexpected error exit code -1 

I tried contacting the server staff to help me with this problem since i could join singleplayer with no problems so i figured it could have been a problem regarding the server. However that turned out to not be the case, the problem lies with the mod called FTBchunks and by removing this mod we could join the sever with no problems. 

Apparently there is a known bug causing this issue with this mod and the creator of that mod haven't found a solution to this problem yet. 

here is a link to the bug: https://github.com/FTBTeam/FTB-Mods-Issues/issues/70

Dont know if it will help to remove the bug or something but i figured it would be good idea to report this problem.

### Reproduction Steps

1. Start minecraft with the mod installed
2. Try to join a server with installed mod 

### Screenshots and Videos

![obrázek_2022-09-05_121406230](https://user-images.githubusercontent.com/112863198/188425818-9edefdcf-5aaf-40b1-b884-ace915a0c352.png)

### Crash Report or Log

https://pastebin.com/HFPwBup3

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v6

### Optifine

No

**Comment by SHXRKIEgg** [comment]
See if restarting the server and modpack amd see if you are able to join?

**Comment by Annihilluss** [comment]
> 

Tried Reinstalling the modpack multiple times, restarting the server, generating a completely new world for the server aswell but the problem persisted.

**Comment by SHXRKIEgg** [comment]
Weird well that fixed it for me but if not for you the best I can suggest is removing Advacned Compass mod client and server side.
