### ISSUE TITLE
Game Crashing after loading all mods

### ISSUE THREAD

**Issue by Alexyo0** [LunaPixelStudios/Fantasy-Realm#13]
### Describe the Bug

https://github.com/LunaPixelStudios/Fantasy-Realm/issues/7

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v6.5

### Optifine

No

### Other Mods

no

**Comment by chorbintime** [comment]
Delete the FancyMenu mod
