### ISSUE TITLE
Crashes when trying to join a server

### ISSUE THREAD

**Issue by Timotylol** [LunaPixelStudios/Fantasy-Realm#15]
### Describe the Bug

When I try to join a server, it just crashes

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

[crash-2022-10-14_22.38.54-client.txt](https://github.com/LunaPixelStudios/Fantasy-Realm/files/9787767/crash-2022-10-14_22.38.54-client.txt)

### Crash Report or Log

https://pastebin.com/RWLEvtqk

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v6.5

### Optifine

No

### Other Mods

nil

**Comment by chorbintime** [comment]
Delete the Advanced Compass mod. If that prevents you from joining the server, just hide the compass via the mod's config, if possible. There also might be a keybind you could press in singleplayer to disable it.

**Comment by Timotylol** [comment]
Thx! it work 😄
