### ISSUE TITLE
Invisible UI

### ISSUE THREAD

**Issue by Herocrossfire** [LunaPixelStudios/Fantasy-Realm#16]
### Describe the Bug

Well my UI is invisible, all the buttons are there and I managed to navigate to create a new world and could see my hotbar. I also managed to open video settings and controls, in video settings everything was there but it of course has the modded GUI, and in controls I saw the list but none of the actual things I could click on.

### Reproduction Steps

1.download mod pack
2.open minecraft through modpack
3.thats it
...

### Screenshots and Videos

[https://insights.gg/dashboard/video/6QPCG9pHaYq2JibzVRS9M8/replay](url)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v7 (newest on curse forge/overwolf app

### Optifine

No

### Other Mods

I haven't added anything yet but I do want to add a few

**Comment by chorbintime** [comment]
Delete the FancyMenu mod for a temporary fix. This is an ongoing issue I'm working with multiple mod developers to permanently fix.

**Comment by Keksuccino** [comment]
Hi! Could you please load the game with FancyMenu enabled and send me your `logs/latest.log` when the invisible menu issues happens? Would help me a lot, thank you!

**Comment by ThatCatNamedHack** [comment]
Good luck Keksuccino, hopefully this will be more helpful than mine!

**Comment by Herocrossfire** [comment]
> Hi! Could you please load the game with FancyMenu enabled and send me your `logs/latest.log` when the invisible menu issues happens? Would help me a lot, thank you!

It is to large for me to send here

**Comment by Keksuccino** [comment]
> > Hi! Could you please load the game with FancyMenu enabled and send me your `logs/latest.log` when the invisible menu issues happens? Would help me a lot, thank you!
> 
> It is to large for me to send here

Is it spamming this error?
`java.lang.RuntimeException: Error computing listener list for de.keksuccino.fancymenu.events.RenderWidgetBackgroundEvent`

If so, please try this build:
https://cdn.discordapp.com/attachments/1028500155399409675/1033834531859464242/fancymenu-1.0.0.jar
and send me your `logs/latest.log` after starting it with that build. If the log is too massive, please upload it to https://gist.github.com, thank you very much!

**Comment by Herocrossfire** [comment]
> > > Hi! Could you please load the game with FancyMenu enabled and send me your `logs/latest.log` when the invisible menu issues happens? Would help me a lot, thank you!
> > 
> > 
> > It is to large for me to send here
> 
> Is it spamming this error? `java.lang.RuntimeException: Error computing listener list for de.keksuccino.fancymenu.events.RenderWidgetBackgroundEvent`
> 
> If so, please try this build: https://cdn.discordapp.com/attachments/1028500155399409675/1033834531859464242/fancymenu-1.0.0.jar and send me your `logs/latest.log` after starting it with that build. If the log is too massive, please upload it to https://gist.github.com, thank you very much!

That fixed it, thank you
[latest.log](https://github.com/LunaPixelStudios/Fantasy-Realm/files/9847713/latest.log)

**Comment by Keksuccino** [comment]
Oh well, that's great to hear! Thank you very much!

**Comment by Herocrossfire** [comment]
> Oh well, that's great to hear! Thank you very much!

well when I opened it a second time it wasn't fixed so I might have just opened the wrong mod pack, sorry about that

**Comment by Keksuccino** [comment]
Can you send me the log of that one, please?

**Comment by Herocrossfire** [comment]
> Can you send me the log of that one, please?

Well I looked through all my modpacks to see which one I opened, and none of them had it so I think I did open the right one and had it only work once. I did add 2 mods to the this modpack (fantasy realm) before I opened it again the issue happened again, so I deleted and redownload it to try to reset it and then switched the fancy menu out again but it was still invisible despite it working the first time, I sent the log of the time when it worked and I can send the log of when I most recently opened it but I'm nit sure if that will help

**Comment by Keksuccino** [comment]
Even if it's the same pack, it would be really great to have a log for when it is NOT working, so I can continue debugging it :) Thank you very much!

**Comment by Herocrossfire** [comment]
> Even if it's the same pack, it would be really great to have a log for when it is NOT working, so I can continue debugging it :) Thank you very much!

Well its to big to send here and I'm not sure how to upload it to github, cause gist which seemed like the way to do it isn't letting me so I'm not sure how to send it

**Comment by Keksuccino** [comment]
pastebin.com would be another site to upload text.

If that doesn't work either, try to upload just the lower half of the log.

**Comment by Herocrossfire** [comment]
> pastebin.com would be another site to upload text.
> 
> If that doesn't work either, try to upload just the lower half of the log.
[file:///C:/Users/Admin/Twitch/Minecraft/Instances/Fantasy%20Realm/logs/latest.log](url)

**Comment by Keksuccino** [comment]
that's not a log, it's just a local file path :D

**Comment by Herocrossfire** [comment]
> that's not a log, it's just a local file path

Did you click on it cause for me it has the text from the log

**Comment by Herocrossfire** [comment]
> > that's not a log, it's just a local file path
> 
> Did you click on it cause for me it has the text from the log

or is that just me being dumb

**Comment by Keksuccino** [comment]
> Did you click on it cause for me it has the text from the log

ofc it works for you, because you have this file at this exact path lmao

**Comment by Herocrossfire** [comment]
> > Did you click on it cause for me it has the text from the log
> 
> ofc it works for you, because you have this file at this exact path lmao

okay so it was just me being dumb, uh how do i actually send the log, if for some resosn you couldnt guess at this point ive never done this before

**Comment by Keksuccino** [comment]
Please upload it to https://gist.github.com or https://pastebin.com .

**Comment by Herocrossfire** [comment]
> Please upload it to https://gist.github.com or https://pastebin.com .

So the issue seems to be that I cant copy and paste the whole thing without the page crashing in both gist and pastebin, and if I try to do it part by part I think its gonna take like an hour or more (I might be overestimating but it will take a while). also when file path that was because I tried to drag and drop the file like I could in gist into pastebin and that didn't work.

**Comment by Herocrossfire** [comment]
> > Please upload it to https://gist.github.com or https://pastebin.com .
> 
> So the issue seems to be that I cant copy and paste the whole thing without the page crashing in both gist and pastebin, and if I try to do it part by part I think its gonna take like an hour or more (I might be overestimating but it will take a while). also when file path that was because I tried to drag and drop the file like I could in gist into pastebin and that didn't work.

Nevermind I can only get a part of it in b4 the page crashes, and by a part of it I mean like 8-10%. I don't now why its so big but it is

**Comment by ThatCatNamedHack** [comment]
Just out of curiosity, what gpu and cpu do you use?

**Comment by Herocrossfire** [comment]
> Just out of curiosity, what gpu and cpu do you use?

This is what it says in the setting about page 
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.59 GHz

**Comment by ThatCatNamedHack** [comment]
It you open Device Manager and look under Display Adapters it will tell you there.

**Comment by Herocrossfire** [comment]
> It you open Device Manager and look under Display Adapters it will tell you there.
Intel(R) HD Graphics 530
NIVIDIA GeForce GTX 970M

**Comment by ThatCatNamedHack** [comment]
Hey same graphics as me! You aren't using a dell latitude by any chance? And there lies the problem I think. Almost everyone I've talked to about this has similar to exactly the same hardware.

**Comment by Herocrossfire** [comment]
> Hey same graphics as me! You aren't using a dell latitude by any chance? And there lies the problem I think. Almost everyone I've talked to about this has similar to exactly the same hardware.

No I don't think I'm using a dell latitude, all I really know is that it says ASUS on under the monitor (its a laptop)

**Comment by ThatCatNamedHack** [comment]
Alrighty then, thanks.

**Comment by Keksuccino** [comment]
@Herocrossfire 
> Nevermind I can only get a part of it in b4 the page crashes, and by a part of it I mean like 8-10%. I don't now why its so big but it is

Is there an error in the second half of the log that gets spammed over and over? Should be always the same error. If so, please try to send me just like 500 lines of this error spam (upload it to https://gist.github.com, should work this time).

**Comment by Herocrossfire** [comment]
> java.lang.RuntimeException:

Here [https://gist.github.com/Herocrossfire/afef3b464f110aad8948882ea13fc44b](url)
is spamming java.lang.RuntimeException: Error computing listener list for de.keksuccino.fancymenu.events.DrawWidgetBackgroundEvent

**Comment by Keksuccino** [comment]
Thank you very much!

Could you please start the game with this new debug build?
https://cdn.discordapp.com/attachments/732269057558052976/1034264426666278922/fancymenu-1.0.0.jar

This one isn't fixing stuff, I just need the debug output, so please send me your `latest.log` after noticing the missing buttons.

And don't keep the game running with this build, just start it, open a menu with missing buttons and close it again, because it spams a lot of debug stuff.

If you don't notice missing buttons, just open a menu that normally has missing buttons and then send me the log.

**Comment by Herocrossfire** [comment]
> Thank you very much!
> 
> Could you please start the game with this new debug build? https://cdn.discordapp.com/attachments/732269057558052976/1034264426666278922/fancymenu-1.0.0.jar
> 
> This one isn't fixing stuff, I just need the debug output, so please send me your `latest.log` after noticing the missing buttons.
> 
> And don't keep the game running with this build, just start it, open a menu with missing buttons and close it again, because it spams a lot of debug stuff.
> 
> If you don't notice missing buttons, just open a menu that normally has missing buttons and then send me the log.

Ok ill do that in a bit playing hollow knight rn, and I'm glad to help

**Comment by Herocrossfire** [comment]
> Thank you very much!
> 
> Could you please start the game with this new debug build? https://cdn.discordapp.com/attachments/732269057558052976/1034264426666278922/fancymenu-1.0.0.jar
> 
> This one isn't fixing stuff, I just need the debug output, so please send me your `latest.log` after noticing the missing buttons.
> 
> And don't keep the game running with this build, just start it, open a menu with missing buttons and close it again, because it spams a lot of debug stuff.
> 
> If you don't notice missing buttons, just open a menu that normally has missing buttons and then send me the log.

I opened it twice and both times the menu was there 
[latest.log](https://github.com/LunaPixelStudios/Fantasy-Realm/files/9856393/latest.log)

**Comment by Keksuccino** [comment]
That's strange. Thank you for testing!
I will push an update without the debug (just the one thing I added, which maybe fixed it).

**Comment by Keksuccino** [comment]
That's the new non-debug build: https://www.curseforge.com/minecraft/mc-mods/fancymenu-forge/files/4050533

If the invisible button problem comes back while using this new build, please send me your `latest.log`, thank you very much for all your help!
