### ISSUE TITLE
Main Menu, settings, and some in-game elements are missing the GUI after launching the modpack.

### ISSUE THREAD

**Issue by Quazza21300** [LunaPixelStudios/Fantasy-Realm#17]
### Describe the Bug

Hiya,

I am encountering an issue with the modpack whenever i launch the pack. My Menus, Some in-game elements just disappear aswell as some of my keybindings. I've tried repairing the modpack, removing resource packs one by one to find if it is them (it isnt) and i have tried reinstalling the modpack over and over (in which the first launch after the reinstall works but every launch after i encounted the issue). Im not sure how to go about fixing it or what the issue causing it would be as i cant find anything in my logs either.

Cheers,

Quazza

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2022-10-23 125113](https://user-images.githubusercontent.com/63824473/197369326-8716cdb4-50d4-47d3-ab68-167da48e861c.png)
![Screenshot 2022-10-23 125127](https://user-images.githubusercontent.com/63824473/197369330-154d3b08-c846-4637-aace-cd3bdfa9d3ff.png)
![Screenshot 2022-10-23 125056](https://user-images.githubusercontent.com/63824473/197369331-a21c5c7a-4a17-4524-9e66-b8ea166ed476.png)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

7

### Optifine

No

**Comment by chorbintime** [comment]
Please zip your logs folder and attach the file here. Delete FancyMenu afterwards to fix this issue.

**Comment by ThatCatNamedHack** [comment]
And just outta curiosity, what cpu and gpu do you use?
