### ISSUE TITLE
Crashing after loading all mods (deleted fancymenu mod)

### ISSUE THREAD

**Issue by Cleanjin** [LunaPixelStudios/Fantasy-Realm#18]
### Describe the Bug

sometimes you can get in But most will not be able to enter.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![1](https://user-images.githubusercontent.com/77272348/197381833-a84d38c4-9494-487f-8afc-524f46c119aa.png)

### Operating System

window 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v7

### Optifine

No

### Other Mods

no

**Comment by chorbintime** [comment]
I cant help with this without a crash report
