### ISSUE TITLE
Mob health bar/shader issue

### ISSUE THREAD

**Issue by natsirt152** [LunaPixelStudios/Fantasy-Realm#19]
### Describe the Bug

When using Fantasy Realm modpack even as a clean install, mobs health will be in the ground when using complimentary shader 4, and complimentary shader reimaged. Upon turning it off the mob health bar returns to above their head. 

Image attached shows where mob health is being placed in ground with the shaders. It's hard to get a better screen shot as the health bar moves as the player and mob moves. So I apologize that its not the best screenshot.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![healthbar](https://user-images.githubusercontent.com/116533377/197437879-dd643532-f56b-4e0e-8e6b-55e766d6c1a4.jpg)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Fantasy Realm v7

### Optifine

No

**Comment by natsirt152** [comment]
To add. Upon looking through the discord. It appears this is an issue on the medieval modpack as well. The issue seems to span back a few months. With little answers, other than repeated links to the suggested shaders. Others have said it will randomly start working, and not working again. It would be nice to be able to use the shaders and see enemy health correctly if possible. Since the modpack says it should work just fine with either shader that's recommended.

**Comment by chorbintime** [comment]
You can try suggesting shader support on Neat's github. There isnt much we could do about this unfortunately.
