### ISSUE TITLE
Mob Health Bar/FTB ultimine shader issue

### ISSUE THREAD

**Issue by MajorGhosty** [LunaPixelStudios/Fantasy-Realm#20]
**Describe the Bug**

When using the complimentary shader 4, and complimentary shader reimaged mob health bars move to a different part of the screen/moves around and FTB Ultimine does the same. The same problem occurred in V6.5 as well.

Reproduction Steps
...

**Screenshots and Videos**

Mob Health bar
![Screenshot 2022-10-23 225832](https://user-images.githubusercontent.com/110222875/197440396-146a07c7-c86d-42ff-85a4-22eb6491b6da.png)
FTBultimine
![image](https://user-images.githubusercontent.com/110222875/197440532-ef63c3c4-a788-4692-91a9-6319b44538b5.png)

**Crash Report or Log**
No response

**Operating System**
Windows 10

**Minecraft Version**
1.16

**Modloader**
Forge

**Modpack Version**
Fantasy Realm V7

**Optifine**
No

**Other Mods**
FTBultimine

**Comment by chorbintime** [comment]
You can try suggesting shader support on Neat's github. There isnt much we could do about this unfortunately.
