### ISSUE TITLE
Citizen and some entity crash my game

### ISSUE THREAD

**Issue by hairryolo** [LunaPixelStudios/Fantasy-Realm#21]
### Describe the Bug

recently playing this modpack I encountered several crashes by entities such as pirates / enderman / citizens of the colony .. I have dedicated more than 5g to the server but nothing to do .. how can I solve?

### Reproduction Steps

1.open the game
2.play the game
3.randomly crash saying unexpected error
...

### Crash Report or Log

https://gist.github.com/hairryolo/91af037a781e7879aba8313d4212fb29

### Operating System

w11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v7

### Optifine

No

**Comment by chorbintime** [comment]
Delete the RoadRunner mod, report on RoadRunner github
