### ISSUE TITLE
right clicking axe of 1000 metals causes ctd

### ISSUE THREAD

**Issue by DougStoker** [LunaPixelStudios/Fantasy-Realm#22]
### Describe the Bug

right clicking axe of 1000 metals causes ctd

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/5HCb8k24

### Operating System

macos catalina

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

7

### Optifine

No

**Comment by chorbintime** [comment]
Does downgrading to an older version of Geckolib fix this?
