### ISSUE TITLE
Program Stops Responding After Constructing Mods

### ISSUE THREAD

**Issue by Bachonin** [LunaPixelStudios/Fantasy-Realm#23]
### Describe the Bug

I have an intermittent problem where the game begins to load up and when it gets to "Constructing Mods" it just stops responding and you have to force quit. I've let it run for about 15 minutes, at all times it keeps utilizing the allocated RAM (I had it set to 12gb).

Out of the 30 odd times I have tried to load it today, I got it to go past this point 2 times to where I can actually play on the server with my wife. There is no crash logs though, so I'm not sure what the issue is. I have deleted Fancy Menu as I saw that as an option, this is when I was able to first get the game to launch, but now it's back at the intermittent issues.

My wife has no issues loading it up on her Windows 10 and I have no issues on my Windows 11 laptop.

### Reproduction Steps

1. Click "Play"
2. Begins to load mods, but stops at "Constructing Mods"
3. Program stops responding altogether
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v7

### Optifine

No

**Comment by chorbintime** [comment]
Can you send a latest.log, please?

**Comment by Bachonin** [comment]
[2022-10-30-5.log.gz](https://github.com/LunaPixelStudios/Fantasy-Realm/files/9914698/2022-10-30-5.log.gz) This is one of the logs where it was throwing the issue. What I ended up doing was using the "Repair Profile" option, starting the game it would give me a higher chance of getting through the Constructing Mods part. I'd say about 75% of the time I can get through as long as I "Repair Profile" first.

**Comment by chorbintime** [comment]
Log has no info. I'd suggest switching to GDLauncher instead of using Curseforge.

**Comment by Bachonin** [comment]
No worries, I appreciate the feedback regardless. I'll give GDLauncher a try if I continue to have issues. For now, I can at least get in most of the time and it only requires a few extra clicks.
