### ISSUE TITLE
Issue with leaves

### ISSUE THREAD

**Issue by sethmont** [LunaPixelStudios/Fantasy-Realm#25]
This problem doesn't apply with the other modded leaves but only for the vanilla leaves it seems. For some reason, all the leaves appear weirdly shaped and have a black boxes protruding outside of them. Seems like the texture is broken maybe. They just look blocky and really bad. I'm not sure if this is a problem with a resource pack or mod. Can anyone help me fix this issue?

**Comment by chorbintime** [comment]
Put leaves textures on fancy. You have them on fast.
