### ISSUE TITLE
Biome Collision

### ISSUE THREAD

**Issue by ChivalKnight** [LunaPixelStudios/Fantasy-Realm#29]
### Describe the Bug

The biome, "Golden_Geelie_Fields" from the mod Feywild is colliding with the biome "Marsh" from the mod Environmental. It does not appear to be colliding with other biomes such as the forest biome from Minecraft. The Marsh does not seem to collide with other biomes either.

### Screenshots and Videos

[https://ibb.co/ZS6WP6D](url)

[https://ibb.co/v4w047j](url)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V7

### Optifine

No

**Comment by ChivalKnight** [comment]
Also, redstone lamps have no texture.

[https://ibb.co/7vCmySD](url)

**Comment by chorbintime** [comment]
Did you ever move between modpack versions? 

Redstone lamps worked for me. Try reloading your textures with F3 + A.
