### ISSUE TITLE
UI: Menu is invisible but accessible

### ISSUE THREAD

**Issue by MayDaySuffers** [LunaPixelStudios/Fantasy-Realm#31]
**Bug Description:**
Upon launching the modpack, all menu buttons are invisible. Buttons are still able to be clicked and interacted, as in creating a word, however no options are visible, so realistically nothing can be changed. Restarting the client does not resolve the issue. Any game file will be provided if necessary, as will be setup specifications.

**Reproductions steps:**
1. Launch the client
2. Observe the issue

**Attachments:**
![Menu 1](https://user-images.githubusercontent.com/120992023/208323554-795f2dc6-3575-44fa-a97e-00b6fd2f3125.PNG)
![Menu 2](https://user-images.githubusercontent.com/120992023/208323561-03003ab1-64f1-4a1d-bb7a-91d1adca0f4c.PNG)
![Menu 3](https://user-images.githubusercontent.com/120992023/208323564-1531e1cc-d35d-4f34-b373-0559d7967639.PNG)

**Operating System:**
Windows 10

**Minecraft Version:**
1.16.5

**Modloader:**
Forge

**Optifine:**
No

**Modpack version:**
v7

**Comment by chorbintime** [comment]
Update the Konkrete and FancyMenu mods, or delete FancyMenu
