### ISSUE TITLE
I can't join a LAN server

### ISSUE THREAD

**Issue by Space-Roach** [LunaPixelStudios/Fantasy-Realm#33]
### Describe the Bug

I'm trying to join a LAN server with my brother but it keeps crashing. I tried looking into it on google but it just said to remove optifine but I never added it in.

### Reproduction Steps

1. Download the mossback
2. Add in a few new textures and some shaders
3. Start up the game
4. Enter a LAN server

### Crash Report or Log

https://pastebin.com/5XSF6bcf

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Fantasy Realm v7

### Optifine

No

**Comment by chorbintime** [comment]
LAN is not supported.
LAN will never be supported.
There is no reason to use LAN.

Please use the serverpack on the modpack's Curseforge page instead. The Readme file details how to selfhost a server.
