### ISSUE TITLE
No Main Overlay

### ISSUE THREAD

**Issue by xNcky** [LunaPixelStudios/Fantasy-Realm#34]
### Describe the Bug

Loaded MC but no main menu
tried restarting didnt work

### Reproduction Steps

1.Start Minecraft
2. Dont see overlay
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/96787228/209437664-a19b378a-2a70-4f4c-8452-f5c18beab5a2.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v7

### Optifine

No

**Comment by chorbintime** [comment]
Update the FancyMenu and Konkrete mods to the latest 1.16.5 version
