### ISSUE TITLE
Required Mod version no longer available.

### ISSUE THREAD

**Issue by Marokarr** [LunaPixelStudios/Fantasy-Realm#35]
### Describe the Bug

The Iter RPG mod no has the required version hosted on curseforge. The only version that is available for download is for Minecraft 1.18.2.

### Reproduction Steps

1. Download modpack
2. mod version no longer available
...

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Fantasy Realm v7

### Optifine

No

### Other Mods

No mods have been added.

**Comment by chorbintime** [comment]
Please complain to the devs of Iter RPG about this. It's not something I can fix. An update will release when the Chaos Awakens mod updates, and I may just remove the mod then. 

Downloading via Curseforge should give you the .jar file necessary, or use the jar in the serverpack.
