### ISSUE TITLE
Game crashed when joining the server

### ISSUE THREAD

**Issue by Coulson51** [LunaPixelStudios/Fantasy-Realm#36]
### Describe the Bug

The game crashed when joining a server.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

[minecraft.log](https://github.com/LunaPixelStudios/Fantasy-Realm/files/10540889/minecraft.log)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v7

### Optifine

No

**Comment by chorbintime** [comment]
How did you install the modpack, step by step?
