### ISSUE TITLE
World doesn't start (Freeze at loading into world)

### ISSUE THREAD

**Issue by NiceGoingChad** [LunaPixelStudios/Fantasy-Realm#38]
### Describe the Bug

Hey there, 

I've played the fantasy realm modpack all day long without any issues, untill i restarted the computer.
My world doesn't want to start / freezes after reading world data. Naturally i tried the following things :

* Updated java before the issue's (Because of lag spikes, currently using java 19
* Removed and reinstalled the game three times
* Removed the Java arguments for optimization and possible java errors
* Replaced the world and placed it back
* Optimized the world & cleared cache (WITH BACKUP)
* Reinstalled Curseforge
* Reinstalled Minecraft
* Was patient, tried to let it load for about a hour.
* Changed ram according to : 8192, 9256, 10256.
* Disabled read-only option in world properties & general file properties
* Updated drivers incase of hardware faults.

Because of my specs i find it highly unlikely that it could be a hardware issue, i had this issue on my laptop with a different modpack but i fixed it there, i did try the same solution for that pack aswell as this one. Nothing works.

The bug seems to occur everytime it has reached the "Reading world data" phase. after of which it'll just turn into the dirt background. 
It started appearing after i was playing the entire day and didn't restart, at some point i was gaining massive FPS drops and
lagspikes which resulted to me restarting the computer

My crashlogs were BEFORE i removed the java arguments.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/i5NSGKdu

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Fantasy realm (Latest)

### Optifine

I used Optifine

**Comment by NiceGoingChad** [comment]
UPDATE : Seems to be somewhat resolved after removing serverconfig files, I however do not see this issue as "SOLVED" As this shouldn't happen. Please retrace what could be wrong with the serverconfigs the world creates @developers

**Comment by chorbintime** [comment]
How did you install the modpack, step by step?

You are not using Optifine. Optifine is incompatible with all of our modpacks and is an all-around bad & unstable mod. It's also a Forge mod so it doesn't work on Fabric.

**Comment by NiceGoingChad** [comment]
Accidently clicked optifine, i meant i don't have optifine i'm using oculus

**Comment by chorbintime** [comment]
How did you install the modpack, step by step?
