### ISSUE TITLE
Outdated Mods

### ISSUE THREAD

**Issue by PassiveRuski** [LunaPixelStudios/Fantasy-Realm#39]
### Describe the Bug

A few mods are outdated and have bugs in them that are already known, please update the modpack.
a bug with minecoloneys, create a coloney, take the town hall, move it to new location, place, delete old coloney, and make a new one, you will have old land and new land, but you cannot get rid of old land, you can see your land claimed with the Map[M] [default button]
a bug with the death history mod where you can dupe your trinkets by clicking the "move to inventory" option while not being at the grave but viewing your history.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/119288498/234919704-2ef8aa5e-728e-4159-a142-25d03d1d86b4.png)
![image](https://user-images.githubusercontent.com/119288498/234919760-9429cbd0-139d-4f04-a6e5-344d71e7bbeb.png)

![image](https://user-images.githubusercontent.com/119288498/234920221-1b72883b-4bb5-468a-8221-882fb9a1a100.png)

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Fantasy Realm v7

### Optifine

No

**Comment by chorbintime** [comment]
the newest update has been in progress for several months but we have been unable to update due to a mod we planned on adding having a major unfixed issue. we are going to release v8 soon anyway.

please do not make a github issue to complain.
