### ISSUE TITLE
World Crashes at Start-Up: Error Code -1

### ISSUE THREAD

**Issue by Parakus** [LunaPixelStudios/Fantasy-Realm#40]
### Describe the Bug

So I'm in this one area working with Minecolonies, when my world suddenly crashes. I try rejoining, and I can join and be in
game for a few minutes, but eventually it crashes again. However, after multiple attempts, I can no longer enter the game.
I've been in this area for some time, so this suddenly started happening out of no where.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/Parakus/f3994db874e74e438afaba4c5e89eda0#file-crash-2023-05-05_13-14-22-server-txt

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

Fantasy Realm v7

### Optifine

No

### Other Mods

UtilitiX-1.16.3-0.1.14

**Comment by chorbintime** [comment]
run /kill @e[type=item]
