### ISSUE TITLE
Server not responding when entering Nether with 2 player corpses

### ISSUE THREAD

**Issue by dubbat** [LunaPixelStudios/Fantasy-Realm#42]
No sure if it is reproduceable, but I can upload the server files if needed if that helps.

I portaled to the nether as usual and it spawned in a bastion. I died several times (early on) but everything seemed to be fine.

When leaving back to the Overworld, I was murdered by Piglins that I had juked thru the portal and forgot about. Since the Overworld was not chunkloaded, they had not transformed to zombie piglins yet. For some reason, my body/corpse ended up in the Nether though I died in the Overworld. I tried going to the other side to check.

I did find the corpse in the Nether. I was not able to access it. I assumed from being in the portal perfectly (later I realized it was simply server was locked). I was unable to use the portal to get back either. I tried to spawn in a diamond pickaxe (to break the portal) and my client had said I timed out and server did not have a response from the command. I could not log back in either. I tried shutting the server down but that also did not respond. I forced the server closed and restarted it and I was able to login and had rolled back my inventory accidentally. I still could not use the portal, I broke the obsidian with my pickaxe and it did not drop the block or break the portal itself, and I was once again unable to get the server to respond to commands to stop or anything. Seems it is deadlocked trying to compute something that it can never finish. No errors.

**Comment by chorbintime** [comment]
Please send logs

**Comment by dubbat** [comment]
> Please send logs

[latest.zip](https://github.com/LunaPixelStudios/Fantasy-Realm/files/11599965/latest.zip)

[debug.zip](https://github.com/LunaPixelStudios/Fantasy-Realm/files/11599968/debug.zip)

Not sure how helpful they will be. Did not see any errors when issue came up (unless there is something in loading).

**Comment by chorbintime** [comment]
Open your playerdata file using the NBTStudio program and change your coordinates to elsewhere, or set your dimension to the overworld

**Comment by dubbat** [comment]
Odd. I guess I didn't hit save in NBTStudio. Still spawned in the_nether and everything was fine. Dropped my duped inventory from forced shutdown, looted my body, went back and forth to and from the nether just fine. Body disappeared inside portal as it was empty.

Maybe it was unrelated? Structure in nether? Elite mob? I wouldn't think so as I was there for a while mining nether quartz. Only bugged when I left, died in overworld, then went back to Nether for my body.

This was all localhost so not a networking issue.

Guess I will close this for now and make a new one if I figure out the cause, or update this one but I doubt I will be dying on the portal again unless I force it.

**Comment by dubbat** [comment]
OK nothing to do with the corpse on the portal at all. Just happened again. Died a few times in a row. Able to make it to the nether, but when I went to my second body, the Hexan Guard was not moving, could not loot old and new body. EXP swirling around me but never being picked up. Eventually client says TimeOut. Don't see any errors in client or server when it locks up.

It's weird because the server responds to me trying to log in, but it doesn't send the full login. Client just says "encrypting". Server will not respond to a /stop command.

I'm assuming this has to do with mob spawn or dying in quick succession, just nothing to do with the portal directly but possibly with dimension changes.

Edit: I believe it is a vanilla(ish?) Bastion as well as whatever structure the Hexan Guard is spawning from. They kinda overlap or something. Seen blackstone as well as netherbrick. They were actually fighting each other or zombie piglins or something. Heard arrows being shot and a sword guy murdered me and I believe whatever was shooting arrows. Server seems fine until I portal to the nether from overworld with a corpse already there.

Edit2: Seeing as tho the Hexan Guard was directly on my body, it seems like the Nether was unloaded when I died, I joined the Nether loading it again exactly where the Hexan Guard was by my body as if he didn't get a single tick in (hadn't walked away). Seems like whatever is happening happens as soon as you change dimensions and specifically the Nether. Possibly to do with Hexan spawns. Possibly to do with player corpses.

**Comment by dubbat** [comment]
Might be unrelated. Just tried to re-create in a singleplayer game. Went creative with cheats. Built nether portal and went in. Created corpses (two just before 1st crash and three on next crash) by punching a zombie piglin in survival. Twice now (even after singeplayer full rollback to portal never existing in overworld) I have died and tried to go back into a portal and it crashes out completely to desktop before even entering the portal (seems to be something with looking at it and getting near it).

[hs_err_pid47524.log](https://github.com/LunaPixelStudios/Fantasy-Realm/files/11619503/hs_err_pid47524.log)
[hs_err_pid47928.log](https://github.com/LunaPixelStudios/Fantasy-Realm/files/11619504/hs_err_pid47928.log)

**Comment by chorbintime** [comment]
Please retry on ATLauncher with Java 18. Follow the guide here https://github.com/LunaPixelStudios/Medieval-MC/wiki/Performance-Guide/

**Comment by dubbat** [comment]
> Please retry on ATLauncher with Java 18. Follow the guide here https://github.com/LunaPixelStudios/Medieval-MC/wiki/Performance-Guide/

OK got it up on that one. Loaded original single player. Crashes when looking at portal.
Made a new world. Made portal. Went into Survival mode. Died twice. Looked at portal slowly from overworld and crashed again.

Weird bug.

2 corpses in Nether crashes client when looking at portal in single player. Possibly locks up server when in multiplayer?

**Comment by dubbat** [comment]
OK I used ATLauncher just for giggles.

I started a new server world.
Gave myself creative mode from server console.
Built a portal.
Gave myself survival mode again from server console.
Went into the nether and killed myself, twice.
Upon third entry (no crash BTW for client like SP), the lava I killed myself on does not damage, no errors on client or server, eventually timed out on client, unable to reconnect, and server no longer responds to commands.

**Comment by chorbintime** [comment]
Are you using Adoptium Java 18 on both server & client?

**Comment by dubbat** [comment]
> Are you using Adoptium Java 18 on both server & client?

CurseForge uses an internal old Java 8 build. (Edit: For ATLauncher, I used Java 17 with no change)
I don't have Java 18 install. Only 19 and 17. I had to modify the ps1 script to launch something else (Java 8 seemed to work) as it was loading Java 17 Adoptium and it was giving a secure JAR error.

Edit: Install Java 18. Still same error about unnamed module and java security.

> [21:57:49] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 18.0.2.1 by Eclipse Adoptium
> Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x1d76aeea) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x1d76aeea
>         at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:45)
>         at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
>         at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:45)
>         at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
>         at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
>         at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
>         at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
>         at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
>         at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
>         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
>         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49)
>         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46)
>         at net.minecraftforge.server.ServerMain.main(ServerMain.java:43)

**Comment by chorbintime** [comment]
My bad, I thought you were on 1.19.2. 

Use Adoptium Java 11 server & clientside.

**Comment by dubbat** [comment]
> My bad, I thought you were on 1.19.2.
> 
> Use Adoptium Java 11 server & clientside.

Yeah, seems to go away with server/client both on Java 11. I will try singleplayer now.

Yeah, I dunno what is going on. Seemed fine in SP for Java 11 as well. Got curious and tried Java 18 again and Java 8 for client and was fine on server.

Went back to CurseForge client (Java 8) and no problems in SP or MP even with MP server running Java 8.

Couple days ago, it was super reproduceable. Now, I can't do it at all on any version.
