### ISSUE TITLE
Crash when specific entity gets rendered

### ISSUE THREAD

**Issue by E3VL** [LunaPixelStudios/Fantasy-Realm#44]
### Describe the Bug

A player loads the entity in question, the server immediately crashes.

### Reproduction Steps

1. Get a illager from IllagerInvasion mod to fire a "skull bolt" at you.
2. 
3. 

### Crash Report or Log

https://pastebin.com/qaXjvSSj

### Operating System

server is on windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
I cant seem to replicate it with any of the IllagerInvasion Mobs, what specific one is it? Does the crash happen all the time or it just happened once? If I had to guess its either Canary or ServerCore causing it.

**Comment by E3VL** [comment]
It happened everytime that player joined aka that entity got rendered

**Comment by SHXRKIEgg** [comment]
The EntityCyclopsEye is the entity thats causing the crash on the player, try removing one or both of the mods to see if he can join back.

**Comment by E3VL** [comment]
I seemed to fix the issue,
I setup command blocks to kill, cyclops eye, cyclops, necromancer from villager invasion, and his spell, skull_bolt.
All of these seem to cause crash issues

/kill @e[type= illagerinvasion:necromancer]
/kill @e[type= illagerinvasion:skull_bolt]
/kill @e[type= iceandfire:cyclops]
/kill @e[type= iceandfire:cylcops_multipart]

**Comment by SHXRKIEgg** [comment]
yeah but thats not the problem, those are only causing a crash due to the Canary or ServerCore mod. So in order to know which one was causing it, you needed to remove one of them so that we know which on is the issue and would need to remove it next update. I was referencing "try removing one or both of the mods" of my message before of Canary or ServerCore causing it.

**Comment by E3VL** [comment]
I removed both servercore and canary, it didnt do anything :\

**Comment by SHXRKIEgg** [comment]
Send the crash report please
