### ISSUE TITLE
[1.18] Enter the nexus quest is missing reward

### ISSUE THREAD

**Issue by whitepyros** [LunaPixelStudios/Fantasy-Realm#45]
### Describe the Bug

The quest "Enter the nexus" under the catagory "The Nexus" is missing a quest reward. Currently it's calling for an ancient vase from deeper and darker which is not in this version of the modpack

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v1.5

### Optifine

No

**Comment by chorbintime** [comment]
will be fixed in next update
