### ISSUE TITLE
Crafting bench doesnt open.

### ISSUE THREAD

**Issue by Clickba** [LunaPixelStudios/Fantasy-Realm#46]
### Describe the Bug

As the title says, everything else in the world seems ok, all my friends can open workbenches and interact with everything.
I can interact with literally everything I've tested so far other than specifically opening a workbench.
Started once i opened the world again (for like the 5th time total) (this world has been played on for around 3 days now).

### Reproduction Steps

1. play the game?
2. open the game?
3. try to open a workbench (wont open at all)
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Fantasy Realm 1.18.2

### Optifine

No

### Other Mods

Valkeries skies
Eureka for valkerie skies

**Comment by chorbintime** [comment]
Retry with added mods removed
