### ISSUE TITLE
Unable to play on LAN

### ISSUE THREAD

**Issue by ParsifalGussov** [LunaPixelStudios/Fantasy-Realm#48]
### Describe the Bug

When another player trying to connect through LAn using Radmin VPN server kicks him after 1-10 sec.

### Reproduction Steps

1. Start owner's world.
2. Connect to Radmin.
3. Use Connet by IP.
4. Got kicked out.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v1.5

### Optifine

No

### Other Mods

Origins
Bucolic Origins
Collection of Singiro Mod
Origins Classes

**Comment by SHXRKIEgg** [comment]
dont use radmin, update to v2 and use the ip lan gives you
