### ISSUE TITLE
Armor stand spinning out 

### ISSUE THREAD

**Issue by JustAnAverageMan** [LunaPixelStudios/Fantasy-Realm#49]
### Describe the Bug

Whenever I'm directly looking at an armor stand it just starts spinning out and it's just really annoying.

### Reproduction Steps

1.Place an armor stand
2. look straight at it 

+ Same problem with different armours on the stand aswell

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

Fantasy Realm v2 HF

### Optifine

No

### Other Mods

No other mods added

**Comment by chorbintime** [comment]
retry on v3

**Comment by guywholikes123** [comment]
can you tell me which mod was causing this? i have my own modpack and im tearing my hair out trying to figure out whats causing this

**Comment by chorbintime** [comment]
all we changed on v3 that could've affected this is just updating all of the mods in the modpack. make sure to set your "Preferred Release Type" to beta before updating, and refresh the modlist after, so beta updates for mods will appear
