### ISSUE TITLE
glitched out by picking up door and cant open anyhting 

### ISSUE THREAD

**Issue by maturecarton90** [LunaPixelStudios/Fantasy-Realm#50]
### Describe the Bug

i accidently shift clicked my door and it picked it up like you would a chest and the door i had down was a door from the Domum Ornamentum mod from the architets cutter. i have the door in my hands but it changes textures like wool, stone, etc. i cant open my inventory switch items on my hotbar or put the item down i had my friend kill me but it sends him flying in the air like he got hit with tnt so he killed me and i opened my body and server crashed got back on and nothing changed. i can still run and jump but thats about it, i tried server restart but nothing has worked at the moment. And it doesnt show the door in my hotbar.

### Reproduction Steps

1.while holding shift 
2.right click on the door then the door will in your hotbar
3. 
...

### Operating System

windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

fantasy realm v3

### Optifine

No

**Comment by chorbintime** [comment]
use the carryon clear command
