### ISSUE TITLE
Isle of Berk Dragons despawn after server crash

### ISSUE THREAD

**Issue by IsaacAnto** [LunaPixelStudios/Fantasy-Realm#51]
### Describe the Bug

Every other day, the server will crash and reset. After which, I will log back in and my tamed dragon that was with me from the Isle of Berk mod disappears. Has happened 3 times and is getting old.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v3

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
We can't help if you don't provide the crash report.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
