### ISSUE TITLE
Ice and Fire dragon did not spawn with above-ground nest

### ISSUE THREAD

**Issue by Duxell** [LunaPixelStudios/Fantasy-Realm#52]
### Describe the Bug

a friend and I approached a roost and there was no dragon anywhere, not sure if there is a chance a roost spawns empty, but figured I should mention it. 

Running no mods outside the pack

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

v3

### Optifine

No

**Comment by chorbintime** [comment]
it probably flew away
