### ISSUE TITLE
Sophisticated Backpacks causing crash at load of Fantasy Realm

### ISSUE THREAD

**Issue by WPBickham1** [LunaPixelStudios/Fantasy-Realm#53]
### Describe the Bug

When Sophisticated Backpacks is added to mod folder it causes the modpack to crash when loading before single/multi game screen.  Backpacked in or out of mod folder has same effect. 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/WPBickham1/f7e66b1f69b74a18bc75da60b10d577d

### Operating System

Windows 10

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

V3

### Optifine

No

### Other Mods

None

**Comment by chorbintime** [comment]
we dont support added mods
