### ISSUE TITLE
Server Bug

### ISSUE THREAD

**Issue by xMatei70** [LunaPixelStudios/Fantasy-Realm#55]
### Describe the Bug

I have a problem with my server I created it and i runned it but I this mod is not working how can i fix it?
![image](https://github.com/user-attachments/assets/9d3a0588-2848-459d-8be4-dfc574252db7)

### Reproduction Steps

1.
2.
3.
...

### Operating System

linux ubuntu

### Minecraft Version

1.18.2

### Modloader

Forge

### Modpack Version

1.18.2 V3

**Comment by chorbintime** [comment]
You don't have the correct files serverside. Make sure to transfer over all folders included in the serverpack, including the config folder.
