### ISSUE TITLE
Game Crashing after loading all mods.

### ISSUE THREAD

**Issue by inuit030** [LunaPixelStudios/Fantasy-Realm#7]
### Describe the Bug

The mods load, music starts playing but after that it says saving world and crashes with the following error code: 

The game crashed whilst rendering screen
Error: java.lang.RuntimeException: Error computing listener list for de.keksuccino.fancymenu.events.RenderWidgetBackgroundEvent
Exit-Code: -1

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v5

### Optifine

No

### Other Mods

I only added ComplementaryShaders_v4.5.1.

**Comment by SHXRKIEgg** [comment]
Does this constantly happen? How much ram did you allocate?

**Comment by chorbintime** [comment]
Delete the FancyMenu mod
