### ISSUE TITLE
Ice and Fire dragons spawn as baby dragons in the overworld.

### ISSUE THREAD

**Issue by batteryguy** [LunaPixelStudios/Fantasy-Realm#8]
### Describe the Bug

Afhter the Update to Fantasy realm V6 the newly generated dragons spawn as baby dragons with their normal tier power.
Upon killing them they will dissapear, only leaving the hitboxes from its wings, tail, and neck behind.

I've tested the modpack with an downgraded version of iceandfire (2.1.10) and the dragons seemed to be back to normal again.

I've also tested the latest version in a different modpack (ice and fire magic) and the updated version seemed to be working there.

There might be an other mod in the modpack causing this issue just like hwyla did in the past.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

V6

### Optifine

No

**Comment by SHXRKIEgg** [comment]
This will only occur when you are not using the serveprack provided. Tested this myself with no issues.

**Comment by Xetzly** [comment]
I'm having the same issue my friend started renting a server off of luna pixel and every dragon i come across besides the ice ones in the overworld are small baby dragons making it impossible to get dragon materials 

also sea serphants are invisible for some reason
