### ISSUE TITLE
A conflict between FTB Chunks and AdvancedCompass crashes your game whenever you join a server

### ISSUE THREAD

**Issue by Thatsmusic99** [LunaPixelStudios/Fantasy-Realm#9]
### Describe the Bug

Seems to be due to https://www.curseforge.com/minecraft/mc-mods/advanced-compass/issues/24, but the developer doesn't seem very responsive to this.

I found whenever I attempted to join a server - world creation not attempted - the game would crash before it could load anything.

### Reproduction Steps

1. Create a server.
2. Start the game up.
3. Attempt to join the server.
4. Once trying to load in, the game crashes.
...

### Crash Report or Log

https://paste.gg/p/anonymous/6cef1b7581d54619a72323a273267195

### Operating System

Windows 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v6

### Optifine

No

**Comment by SHXRKIEgg** [comment]
I believe restarting the Modpack makes it so you can join again. Right now I cant fix it due to the mod not doing an update addressing this

**Comment by Thatsmusic99** [comment]
I would presume by restart you mean just kicking the game up again? If so, I'm afraid I've had no dice with it since it also crashes consistently when entering singleplayer. If nothing can be done about it, then alas. I was mainly trying to test server connectivity, which otherwise worked in the end.

I know a later version (1.18.2) of FTB Chunks fixed the conflict but it wasn't backported.

**Comment by SHXRKIEgg** [comment]
Does a server restart work?

**Comment by Thatsmusic99** [comment]
Good question. It's a bit late today for me but I'll verify that tomorrow. I didn't consider that since it all seemed to be clientside, given it was also failing for singleplayer.
